insert into detalles_Top_Hombres (id_registro_hombres, id_leaderboard, id_atleta, dia, mes, puesto_top) values (1, 2, 26, 7, 1, 83);
insert into detalles_Top_Hombres (id_registro_hombres, id_leaderboard, id_atleta, dia, mes, puesto_top) values (2, 2, 11, 23, 2, 97);
insert into detalles_Top_Hombres (id_registro_hombres, id_leaderboard, id_atleta, dia, mes, puesto_top) values (3, 7, 28, 12, 2, 87);
insert into detalles_Top_Hombres (id_registro_hombres, id_leaderboard, id_atleta, dia, mes, puesto_top) values (4, 4, 23, 27, 4, 40);
insert into detalles_Top_Hombres (id_registro_hombres, id_leaderboard, id_atleta, dia, mes, puesto_top) values (5, 10, 22, 12, 10, 5);
insert into detalles_Top_Hombres (id_registro_hombres, id_leaderboard, id_atleta, dia, mes, puesto_top) values (6, 1, 20, 30, 11, 22);
insert into detalles_Top_Hombres (id_registro_hombres, id_leaderboard, id_atleta, dia, mes, puesto_top) values (7, 9, 25, 15, 2, 39);
insert into detalles_Top_Hombres (id_registro_hombres, id_leaderboard, id_atleta, dia, mes, puesto_top) values (8, 16, 2, 29, 7, 33);
insert into detalles_Top_Hombres (id_registro_hombres, id_leaderboard, id_atleta, dia, mes, puesto_top) values (9, 19, 20, 31, 10, 69);
insert into detalles_Top_Hombres (id_registro_hombres, id_leaderboard, id_atleta, dia, mes, puesto_top) values (10, 9, 18, 19, 7, 13);
insert into detalles_Top_Hombres (id_registro_hombres, id_leaderboard, id_atleta, dia, mes, puesto_top) values (11, 8, 23, 18, 10, 96);
insert into detalles_Top_Hombres (id_registro_hombres, id_leaderboard, id_atleta, dia, mes, puesto_top) values (12, 1, 5, 23, 2, 65);
insert into detalles_Top_Hombres (id_registro_hombres, id_leaderboard, id_atleta, dia, mes, puesto_top) values (13, 3, 19, 12, 1, 15);
insert into detalles_Top_Hombres (id_registro_hombres, id_leaderboard, id_atleta, dia, mes, puesto_top) values (14, 20, 9, 30, 3, 32);
insert into detalles_Top_Hombres (id_registro_hombres, id_leaderboard, id_atleta, dia, mes, puesto_top) values (15, 9, 10, 19, 2, 57);
insert into detalles_Top_Hombres (id_registro_hombres, id_leaderboard, id_atleta, dia, mes, puesto_top) values (16, 3, 23, 25, 4, 82);
insert into detalles_Top_Hombres (id_registro_hombres, id_leaderboard, id_atleta, dia, mes, puesto_top) values (17, 3, 9, 15, 9, 58);
insert into detalles_Top_Hombres (id_registro_hombres, id_leaderboard, id_atleta, dia, mes, puesto_top) values (18, 5, 28, 24, 2, 27);
insert into detalles_Top_Hombres (id_registro_hombres, id_leaderboard, id_atleta, dia, mes, puesto_top) values (19, 3, 20, 1, 11, 14);
insert into detalles_Top_Hombres (id_registro_hombres, id_leaderboard, id_atleta, dia, mes, puesto_top) values (20, 1, 16, 29, 9, 78);

SELECT * FROM detalles_Top_Hombres;