INSERT INTO ESPECIALIDAD (ID_ESPECIALIDAD, TIPO_ESPECIALIDAD) VALUES (1,'AMRAP');
INSERT INTO ESPECIALIDAD (ID_ESPECIALIDAD, TIPO_ESPECIALIDAD) VALUES (2,'EMOM');
INSERT INTO ESPECIALIDAD (ID_ESPECIALIDAD, TIPO_ESPECIALIDAD) VALUES (3,'FOR TIME');
INSERT INTO ESPECIALIDAD (ID_ESPECIALIDAD, TIPO_ESPECIALIDAD) VALUES (4,'TABATA');
INSERT INTO ESPECIALIDAD (ID_ESPECIALIDAD, TIPO_ESPECIALIDAD) VALUES (5,'FOR MAX WEIGHT');
